export const actionsTypes = {
 FETCHING_START: "FETCHING_START",
 FETCHING_SUCCESS: "FETCHING_SUCCESS",
 FETCHING_ERROR: "FETCHING_ERROR",
 ADD_TO_CART: "ADD_TO_CART",
 REMOVE_FROM_CART:"REMOVE_FROM_CART",
 ADD_TO_WISH_LIST: "ADD_TO_WISH_LIST",
 REMOVE_FROM_WISH_LIST: "REMOVE_FROM_WISH_LIST",
};